#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

kSQLiteServerThriftError = -1
kSQLiteResultSetIndexOutOfBounds = -2
kSQLiteResultSetElementNotFound = -3
kSQLiteNotSupportedType = -4
kSQLiteServerInternalError = -5
kSQLiteMachineUnderMaintenanceError = -6
kSQLiteUserUnderMaintenanceError = -7
